### ISSUE TITLE
mailsy hangs, if subject and body are empty

### ISSUE THREAD

**Issue by mgiugliano** [BalliAsghar/Mailsy#16]
```
mailsy m
```

gets stuck with 
```
opening...spinner is not defined
opening...
```

when both body and subject of the received email are empty (from my tests).

I am on macOs (14.4.1 (23E224)), Homebrew (4.2.18), npm (10.5.0), and mailsy (4.0.1).

**Comment by svenjr** [comment]
I am also seeing this issue

```
mailsy m
? Select an email 1. meteoblue - Confirm email address - From:  info@meteoblue.com
⠸ fetching...spinner is not defined
⠙ fetching...
```

**Comment by BalliAsghar** [comment]
Fixed in latest release!
