### ISSUE TITLE
DNS Resolution Issues with a chosen domain

### ISSUE THREAD

**Issue by svenjr** [BalliAsghar/Mailsy#19]
I have generated 3 emails in a row in the last half hour and the are all using `****@talemarketing.com` but I am trying to sign up to a site with them and get a confirmation email with no luck. After trying to send an email to myself, it bounced back with a domain issue, see below:

![Screenshot 2024-07-22 at 11 18 49](https://github.com/user-attachments/assets/3efb10b7-576f-4b7f-8eb6-c4f6cb48cb98)

Looks to be a problem with this specific domain. I will try to generate one that does not contain this

**Comment by dderemiah** [comment]
talemarketing.com has no DNS MX record and will not work as an e-mail domain until that is fixed.

**Comment by mikekellyonline** [comment]
I wonder if it is worth creating a public dns server for this? I wonder if a use case for this could be using free virtual servers through some of the main online companies?

**Comment by Mikekellydev** [comment]
The DNS issue has been resolved. The application works.  I tested an email with text and photos successfully. I recommend closing this issue.

**Comment by svenjr** [comment]
I can also confirm it works now! Closing! Thanks
