### ISSUE TITLE
Emails don't open after fetching 

### ISSUE THREAD

**Issue by urizennnn** [BalliAsghar/Mailsy#22]
I have an alias ```fetch``` which retrieves my mail and then i hit the enter key but it doesn't open the mail.

**Comment by BalliAsghar** [comment]
This is not an issue with Mailsy. Please ensure you are setting up the alias correctly.

**Comment by ljis120301** [comment]
I'm sorry for being stupid. I am having the same issue on Fedora after installing using the brew package manager. By setting up the proper aliases what steps need to be taken to do that?
